globalParam = struct(...
    'MotionModel',                  @ParticleFilterMotionModel, ...
    'FeatureExtractor',             @LabPartHistogramExtractor, ...
    'ConfidenceJudger',             @ClassificationScoreJudger, ...
    'ObservationModelTrain',        @LogisticRegressionTrain, ...
    'ObservationModelTest',         @LogisticRegressionTest, ...
    'NegSampler',                   @NegSlidingWindowSampler, ...
    'PosSampler',                   @PosSlidingWindowSampler ... 
);